version: '3'

services:
  color:
    build: .
    container_name: color-backend
    ports:
    - "8009:8009"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - MONGO_DB_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_DB_PASSWORD=${MONGO_DB_PASSOWRD}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - SECRET=${SECRET}
      - ACCESS_EXP=${ACCESS_EXP}
      - REFRESH_EXP=${REFRESH_EXP}