spring:
  data:
    mongodb:
      host: ${DB_HOST}
      port: ${DB_PORT}
      database: ${DB_NAME}
      auto-index-creation: true   # ddl-auto
      authentication-database: admin
      username: ${MONGO_DB_USERNAME}
      password: ${MONGO_DB_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
auth:
  secret: ${SECRET:dsafsaf}
  exp:
    access: ${ACCESS_EXP:10000}
    refresh: ${REFRESH_EXP:2010210}

server:
  port: 8009
logging:
  level:
    org.springframework.data.mongodb.repository.query: DEBUG