spring:
  data:
    mongodb:
      host: ${DB_HOST:localhost}
      port: ${DB_PORT:27017}
      database: ${DB_NAME:test}
      auto-index-creation: true   # ddl-auto
      authentication-database: admin
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:201420hjh@dsm.hs.kr}
    password: ${MAIL_PASSWORD:wjdgus12}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
  profiles:
    active: local
auth:
  secret: ${SECRET:dsafsaf}
  exp:
    access: ${ACCESS_EXP:10000}
    refresh: ${REFRESH_EXP:2010210}